---
name: nginx
director_uuid: 92685ef7-072d-44b0-9b44-dde72d375932

releases:
- name: nginx-dev
  version:  latest

networks:
- cloud_properties:
    net_id: c93972b7-22a8-4e5f-8a1e-24074560a4dc
    security_groups: []
  name: floating
  type: vip
- name: default
  subnets:
  - cloud_properties:
      net_id: 2adc8497-bdf9-4be7-9d43-399d22555640
      security_groups:
      - default
    dns:
    - 200.129.69.166
    - 200.129.69.136
    gateway: 10.17.0.1
    range: 10.17.0.0/24
    reserved:
    - 10.17.0.2 - 10.17.0.199
    static:
    - 10.17.0.200 - 10.17.0.205
  type: manual

resource_pools:
- name: default
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties:
    instance_type: s1.small

compilation:
  workers: 2
  network: default
  cloud_properties:
    instance_type: s1.small

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: nginx
  templates:
  - name: nginx
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.17.0.202
