---
name: nginx
director_uuid: 92685ef7-072d-44b0-9b44-dde72d375932

releases:
- name: nginx
  version:  latest

networks:
- cloud_properties:
    net_id: c93972b7-22a8-4e5f-8a1e-24074560a4dc
    security_groups: []
  name: floating
  type: vip
- name: default
  subnets:
  - cloud_properties:
      net_id: 2adc8497-bdf9-4be7-9d43-399d22555640
      security_groups:

resource_pools:
- name: default
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties:
    instance_type: s1.small

compilation:
  workers: 1
  network: default
  cloud_properties:
    instance_type: s1.small

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: nginx
  templates:
  - name: nginx
  instances: 1
  resource_pool: default
  networks:
  - name: default
